package com.gmail.smjcrane.ultimateidle;

public class Words {

    public static String[] encouragement = {
            "You’ve got it!",
            "Sensational!",
            "You’re doing fine!",
            "Super!",
            "That’s right!",
            "Good going!",
            "That’s good!",
            "Excellent!",
            "Wonderful!",
            "Work of art!",
            "Good work!",
            "Best ever!",
            "Superb!",
            "Exactly right!",
            "Very good!",
            "Perfect!",
            "Better than ever!",
            "That’s it!",
            "Keep it up!",
            "Fine!",
            "Outstanding!",
            "Great!",
            "Nice going!",
            "I knew you could do it!",
            "Fantastic!",
            "Congratulations!",
            "Tremendous!",
            "Good going!",
            "That’s great!",
            "I’m impressed!",
            "Keep working on it!",
            "Now you have it!" ,
            "Marvelous!",
            "I like that!",
            "Cool!",
            "Way to go!",
            "Beautiful!",
            "You’ve got the hang of it!",
            "Super-Duper!",
            "You did it that time!",
            "Right on!",
            "Better and better!",
            "You’re on the right track!",
            "Nice going!",
            "Good job!",
            "That’s really nice!",
            "Wow!",
            "That’s the way!",
            "Keep up the good work!",
            "You make it look easy!",
            "Terrific!",
            "Nothing can stop you!",
            "Coming along nicely!",
            "So big!",
            "What a huge number!",
            "Amazing!"
    };
}
